# Generated by Django 5.2.5 on 2025-08-16 15:10

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.IntegerField(choices=[(1, 'Wood'), (2, 'Stone'), (3, 'Gold'), (4, 'Tool'), (5, 'Food')])),
                ('quantity', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structure_type', models.IntegerField(choices=[(1, 'Tree'), (2, 'Rock'), (3, 'Building'), (4, 'Flag'), (5, 'City')])),
                ('lat', models.FloatField(help_text='Latitude coordinate')),
                ('lon', models.FloatField(help_text='Longitude coordinate')),
                ('hp', models.IntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroundItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('lat', models.FloatField(help_text='Latitude coordinate')),
                ('lon', models.FloatField(help_text='Longitude coordinate')),
                ('expires_at', models.DateTimeField(help_text='When item despawns')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='NatureStructure',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.structure')),
                ('last_harvest', models.DateTimeField(default=datetime.datetime.now)),
                ('respawn_time', models.IntegerField(default=3600, help_text='Seconds until respawn')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.structure',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField(help_text='Latitude coordinate')),
                ('lon', models.FloatField(help_text='Longitude coordinate')),
                ('hp', models.IntegerField(default=100, help_text='Hit points')),
                ('gold', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('center_lat', models.FloatField(help_text='Center latitude for movement range')),
                ('center_lon', models.FloatField(help_text='Center longitude for movement range')),
                ('avatar', models.IntegerField(default=0, help_text='Avatar type')),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('bio', models.CharField(blank=True, default='', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('move', 'Player Movement'), ('harvest', 'Resource Harvest'), ('build', 'Structure Built'), ('combat', 'Combat Action')], max_length=20)),
                ('data', models.JSONField(help_text='Event-specific data')),
                ('processed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='main.player')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='PlayerStructure',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.structure')),
                ('level', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='main.player')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.structure',),
        ),
    ]
