# Generated by Django 5.2.5 on 2025-08-17 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='heal_amount',
            field=models.IntegerField(default=0, help_text='HP healing amount'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='heal_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of max HP to heal (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='mana_restore',
            field=models.IntegerField(default=0, help_text='Mana restoration amount'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='stamina_restore',
            field=models.IntegerField(default=0, help_text='Stamina restoration amount'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('combat', 'Combat Event'), ('trade', 'Trade Event'), ('level_up', 'Level Up'), ('item_found', 'Item Found'), ('player_nearby', 'Player Nearby'), ('resource_gathered', 'Resource Gathered'), ('loot_dropped', 'Loot Dropped')], max_length=20),
        ),
        migrations.CreateModel(
            name='ResourceNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('tree', 'Tree'), ('iron_mine', 'Iron Mine'), ('gold_mine', 'Gold Mine'), ('stone_quarry', 'Stone Quarry'), ('herb_patch', 'Herb Patch'), ('ruins', 'Ancient Ruins'), ('cave', 'Cave'), ('well', 'Water Well'), ('farm', 'Farm'), ('berry_bush', 'Berry Bush')], max_length=20)),
                ('lat', models.FloatField(help_text='Resource latitude')),
                ('lon', models.FloatField(help_text='Resource longitude')),
                ('level', models.IntegerField(default=1, help_text='Resource level (1-10)')),
                ('quantity', models.IntegerField(default=5, help_text='Current available quantity')),
                ('max_quantity', models.IntegerField(default=5, help_text='Maximum quantity when full')),
                ('last_harvested', models.DateTimeField(blank=True, null=True)),
                ('harvest_count', models.IntegerField(default=0, help_text='Times harvested')),
                ('respawn_time', models.IntegerField(default=60, help_text='Minutes to respawn')),
                ('base_experience', models.IntegerField(default=10)),
                ('is_depleted', models.BooleanField(default=False)),
                ('created_by_system', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rpg_resource_nodes',
                'unique_together': {('lat', 'lon')},
            },
        ),
        migrations.CreateModel(
            name='ResourceHarvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'Harvesting'), ('completed', 'Completed'), ('interrupted', 'Interrupted'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('experience_gained', models.IntegerField(default=0)),
                ('gold_gained', models.IntegerField(default=0)),
                ('items_gained', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=5, help_text='Time to complete harvest')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_harvests', to='main.character')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='main.resourcenode')),
            ],
            options={
                'db_table': 'rpg_resource_harvests',
            },
        ),
    ]
