# Generated by Django 5.2.5 on 2025-08-16 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_criminalactivity_weapon_remove_player_gold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Flag name/description', max_length=100)),
                ('flag_type', models.CharField(choices=[('territory', 'Territory Flag'), ('family', 'Family Flag'), ('outpost', 'Outpost'), ('stronghold', 'Stronghold'), ('watchtower', 'Watchtower')], default='territory', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_attack', 'Under Attack'), ('captured', 'Recently Captured'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('lat', models.FloatField(help_text='Flag latitude')),
                ('lon', models.FloatField(help_text='Flag longitude')),
                ('level', models.IntegerField(default=1, help_text='Flag level (1-10)')),
                ('hp', models.IntegerField(default=1000, help_text='Flag hit points')),
                ('max_hp', models.IntegerField(default=1000, help_text='Maximum hit points')),
                ('defense_rating', models.IntegerField(default=50, help_text='Defense strength')),
                ('income_per_hour', models.IntegerField(default=500, help_text='Hourly income generated')),
                ('influence_radius', models.IntegerField(default=100, help_text='Influence radius in meters')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('last_attacked', models.DateTimeField(blank=True, null=True)),
                ('invulnerable_until', models.DateTimeField(blank=True, help_text='Protection period after placement', null=True)),
                ('placement_cost', models.IntegerField(default=50000, help_text='Cost to place this flag')),
                ('upgrade_cost', models.IntegerField(default=10000, help_text='Cost to upgrade to next level')),
                ('controlling_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_flags', to='main.family')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_flags', to='main.player')),
            ],
            options={
                'unique_together': {('lat', 'lon')},
            },
        ),
        migrations.CreateModel(
            name='FlagAttack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing Attack'), ('in_progress', 'Attack in Progress'), ('successful', 'Attack Successful'), ('failed', 'Attack Failed'), ('defended', 'Successfully Defended')], default='preparing', max_length=20)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('attack_strength', models.IntegerField(default=100, help_text='Total attack power')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30, help_text='Attack duration')),
                ('attacker_casualties', models.IntegerField(default=0)),
                ('defender_casualties', models.IntegerField(default=0)),
                ('money_gained', models.IntegerField(default=0)),
                ('reputation_gained', models.IntegerField(default=0)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_attacks', to='main.player')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='main.flag')),
                ('supporting_players', models.ManyToManyField(blank=True, related_name='supported_flag_attacks', to='main.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlagUpgrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upgrade_type', models.CharField(choices=[('level', 'Level Increase'), ('defense', 'Defense Boost'), ('income', 'Income Boost'), ('range', 'Influence Range Increase'), ('special', 'Special Ability')], max_length=20)),
                ('old_value', models.IntegerField(default=0)),
                ('new_value', models.IntegerField(default=0)),
                ('cost_paid', models.IntegerField(default=0)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='main.flag')),
                ('upgraded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_upgrades', to='main.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
