# Generated by Django 5.2.5 on 2025-08-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_npc_npccombat_resourcenode_resourceharvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='spawned_on_flag',
            field=models.ForeignKey(blank=True, help_text='Flag this NPC is defending (null for legacy NPCs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spawned_npcs', to='main.flag'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='respawn_time',
            field=models.IntegerField(default=300, help_text='Seconds to respawn after death (5 minutes)'),
        ),
    ]
