# Generated by Django 5.2.5 on 2025-08-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_buildingtype_flagcolor_buildingtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='flag_color',
            field=models.ForeignKey(blank=True, help_text="User's chosen flag color", null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.flagcolor'),
        ),
    ]
