# Generated by Django 5.2.5 on 2025-08-19 21:15
# Remove flag_color field from Character model since flag system is removed

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_character_flag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='flag_color',
        ),
    ]
