# Generated by Django 5.2.5 on 2025-08-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20250819_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='move_center_lat',
            field=models.FloatField(blank=True, help_text='Movement center latitude', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='move_center_lon',
            field=models.FloatField(blank=True, help_text='Movement center longitude', null=True),
        ),
    ]
