# Generated by Django 5.2.5 on 2025-08-20 00:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_character_move_center_lat_character_move_center_lon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('lat', models.FloatField(db_index=True)),
                ('lon', models.FloatField(db_index=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('hp_current', models.PositiveIntegerField(default=100)),
                ('hp_max', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_attack', 'Under Attack'), ('capturable', 'Capturable'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('uncollected_balance', models.BigIntegerField(default=0)),
                ('income_per_hour', models.IntegerField(default=10)),
                ('upkeep_per_day', models.IntegerField(default=5)),
                ('last_income_at', models.DateTimeField(auto_now_add=True)),
                ('last_upkeep_at', models.DateTimeField(auto_now_add=True)),
                ('capture_window_ends_at', models.DateTimeField(blank=True, null=True)),
                ('protection_ends_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rpg_territory_flags',
            },
        ),
        migrations.CreateModel(
            name='FlagLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('upkeep', 'Upkeep'), ('collect', 'Collect'), ('adjust', 'Adjust')], max_length=16)),
                ('amount', models.BigIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='main.territoryflag')),
            ],
            options={
                'db_table': 'rpg_flag_ledger',
            },
        ),
        migrations.CreateModel(
            name='FlagAttack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('damage', models.IntegerField(default=0)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='main.territoryflag')),
            ],
            options={
                'db_table': 'rpg_flag_attacks',
            },
        ),
        migrations.AddIndex(
            model_name='territoryflag',
            index=models.Index(fields=['lat', 'lon'], name='rpg_territo_lat_38d8cb_idx'),
        ),
    ]
