# Generated by Django 5.2.5 on 2025-08-21 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_territoryflag_flagledger_flagattack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cleared', 'Cleared'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('target_count', models.PositiveIntegerField(default=5)),
                ('defeated_count', models.PositiveIntegerField(default=0)),
                ('active_monster_ids', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_runs', to='main.character')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='main.territoryflag')),
            ],
            options={
                'db_table': 'rpg_flag_runs',
                'indexes': [models.Index(fields=['character', 'flag', 'status'], name='rpg_flag_ru_charact_89d7bc_idx')],
            },
        ),
    ]
