# Generated by Django 5.2.5 on 2025-08-22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_flagrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='territoryflag',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]

