# Generated by Django 5.2.5 on 2025-08-22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_territoryflag_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstertemplate',
            name='drop_pool',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resourcenode',
            name='drop_pool',
            field=models.JSONField(default=list),
        ),
    ]

