# Generated by Django 5.2.5 on 2025-08-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_drop_pools'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='class_type',
            field=models.CharField(choices=[('cyber_warrior', 'Cyber Warrior'), ('neural_hacker', 'Neural Hacker'), ('mech_pilot', 'Mech Pilot'), ('bio_synth', 'Bio Synth'), ('quantum_rogue', 'Quantum Rogue'), ('void_sorcerer', 'Void Sorcerer')], default='cyber_warrior', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='flag_color',
            field=models.ForeignKey(blank=True, help_text="User's chosen flag color", null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.flagcolor'),
        ),
    ]
