# Generated by Django 5.2.5 on 2025-08-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_character_class_type_character_flag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='unspent_stat_points',
            field=models.IntegerField(default=0),
        ),
    ]
