# Generated by Django 5.2.5 on 2025-08-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_character_unspent_stat_points'),
    ]

    operations = [
        # Cleanup legacy PK table rows with broken FKs that can cause SQLite constraint checks to fail
        # 1) Remove orphaned zones that point to non-existent flags
        migrations.RunSQL(
            sql=(
                "DELETE FROM pk_territory_zones "
                "WHERE flag_id NOT IN (SELECT id FROM pk_territory_flags)"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 2) Remove flags that point to non-existent characters (legacy schema)
        migrations.RunSQL(
            sql=(
                "DELETE FROM pk_territory_flags "
                "WHERE owner_id NOT IN (SELECT id FROM rpg_characters)"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 3) Remove any zones that now became orphaned after deleting invalid flags
        migrations.RunSQL(
            sql=(
                "DELETE FROM pk_territory_zones "
                "WHERE flag_id NOT IN (SELECT id FROM pk_territory_flags)"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='resourcenode',
            name='resource_type',
            field=models.CharField(choices=[('tree', 'Neon Tree'), ('iron_mine', 'Plasma Mine'), ('gold_mine', 'Stellar Crystal Vein'), ('stone_quarry', 'Alloy Quarry'), ('herb_patch', 'Mutant Herb Cluster'), ('ruins', 'Ancient Alien Ruins'), ('cave', 'Void-Touched Cave'), ('well', 'Hydration Nexus'), ('farm', 'Biofarm'), ('berry_bush', 'Energy Berry Bush')], max_length=20),
        ),
    ]
