# Generated by Django 5.2.5 on 2025-09-02 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_resourcenode_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='downed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='respawn_available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='agility_penalty_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pvecombat',
            name='last_turn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvecombat',
            name='turn_interval_seconds',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='HealingClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_tick_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healing_claims', to='main.character')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healing_claims', to='main.resourcenode')),
            ],
            options={
                'db_table': 'rpg_healing_claims',
                'indexes': [models.Index(fields=['resource', 'active'], name='rpg_healing_resourc_772e26_idx'), models.Index(fields=['character', 'active'], name='rpg_healing_charact_2eec54_idx')],
            },
        ),
    ]
