# Generated by Django 5.2.5 on 2025-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_character_downed_at_character_respawn_available_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_jump_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='territoryflag',
            name='hex_q',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='territoryflag',
            name='hex_r',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='territoryflag',
            unique_together={('hex_q', 'hex_r')},
        ),
    ]
